# Generated by Django 3.2.5 on 2021-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_issubscribed'),
        ('frequencymasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencymaster',
            name='discount_per',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.RemoveField(
            model_name='frequencymaster',
            name='product',
        ),
        migrations.AddField(
            model_name='frequencymaster',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
