# Generated by Django 3.2.5 on 2021-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencymasters', '0002_auto_20210823_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencymaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
