# Generated by Django 3.2.5 on 2021-08-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210802_1450'),
        ('paymentlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='customerid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
        ),
    ]
