# Generated by Django 3.2.5 on 2021-08-17 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlogs', '0002_paymentlog_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='paymentdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=6),
        ),
    ]
