# Generated by Django 3.2.5 on 2021-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlogs', '0003_auto_20210817_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='paymentdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
