# Generated by Django 3.2.5 on 2021-07-19 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20210719_1348'),
        ('othermasters', '0003_alter_citymaster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('schedule_delivery_date', models.DateTimeField(default=datetime.datetime.now)),
                ('shipping_date', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_address', models.TextField()),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('tracking_number', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othermasters.saleperson')),
            ],
        ),
    ]
