# Generated by Django 3.2.5 on 2021-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_staff',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=[('raj', 'raj')]),
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('buynow', 'Regular'), ('subscription', 'Subscription')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_person',
            field=models.CharField(choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], max_length=200, null=True),
        ),
    ]
