# Generated by Django 3.2.5 on 2021-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210719_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_staff',
            field=models.CharField(blank=True, choices=[('raj', 'raj')], max_length=200, null=True),
        ),
    ]
