# Generated by Django 3.2.5 on 2021-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMaster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivery_received', 'Delivery Received'), ('delivery_scheduled', 'Delivery Scheduled'), ('out_for_elivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=200),
        ),
    ]
