# Generated by Django 3.2.5 on 2021-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210720_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepaid_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
