# Generated by Django 3.2.5 on 2021-08-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_staff',
            field=models.CharField(blank=True, choices=[('raj', 'raj'), ('ramesh', 'ramesh')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
