# Generated by Django 3.2.5 on 2021-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societymasters', '0004_alter_societymaster_assign_sale_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymaster',
            name='assign_sale_person',
            field=models.CharField(choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], max_length=200, null=True),
        ),
    ]
