# Generated by Django 3.2.5 on 2021-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperson',
            name='designation',
            field=models.CharField(choices=[('sales_person', 'Sales Person'), ('delivery_guy', 'Delivery Guy')], max_length=20),
        ),
    ]
