# Generated by Django 3.2.5 on 2021-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0002_alter_staffperson_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffperson',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staffperson',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
