# Generated by Django 3.2.5 on 2021-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0003_auto_20210719_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperson',
            name='pincode',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
