# Generated by Django 3.2.5 on 2021-07-19 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0004_alter_staffperson_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperson',
            name='pincode',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
