# Generated by Django 3.2.5 on 2021-07-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0006_auto_20210720_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffperson',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='dateofjoining',
        ),
    ]
