# Generated by Django 3.2.5 on 2021-07-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0007_auto_20210720_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStaffRoster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staffpersons.staffperson',),
        ),
    ]
