# Generated by Django 3.2.5 on 2021-07-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0008_deliverystaffroster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStaffRoster',
        ),
        migrations.CreateModel(
            name='DeliveryStaffRosterMaster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staffpersons.staffperson',),
        ),
    ]
