# Generated by Django 3.2.5 on 2021-07-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0009_auto_20210720_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStaffRosterMaster',
        ),
    ]
