# Generated by Django 3.2.5 on 2021-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='society',
        ),
    ]
