# Generated by Django 3.2.5 on 2021-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.TextField(default='Desciption'),
        ),
    ]
