# Generated by Django 3.2.5 on 2021-07-19 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20210719_1348'),
        ('othermasters', '0003_alter_citymaster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(default=datetime.datetime.now)),
                ('subscription_start', models.DateTimeField(default=datetime.datetime.now)),
                ('subscription_end', models.DateTimeField(blank=True)),
                ('delivery_address', models.TextField()),
                ('product_subscried', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('resume_subscription', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othermasters.saleperson')),
            ],
        ),
    ]
