# Generated by Django 3.2.5 on 2021-07-19 08:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_renewal_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
