# Generated by Django 3.2.5 on 2021-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210719_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
