# Generated by Django 3.2.5 on 2021-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_subscription_renewal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sales_person',
        ),
    ]
