# Generated by Django 3.2.5 on 2021-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery_staff',
            field=models.CharField(choices=[(2, 'raj')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sales_person',
            field=models.CharField(choices=[(1, 'nikhil')], max_length=200, null=True),
        ),
    ]
