# Generated by Django 3.2.5 on 2021-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210719_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_staff',
            field=models.CharField(choices=[('delivery_guy', 'raj')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sales_person',
            field=models.CharField(choices=[('sales_person', 'nikhil')], max_length=200, null=True),
        ),
    ]
