# Generated by Django 3.2.5 on 2021-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20210719_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sales_person',
            field=models.CharField(choices=[('sales_person', 'nikhil'), ('sales_person', 'ganesh')], max_length=200, null=True),
        ),
    ]
