# Generated by Django 3.2.5 on 2021-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_staff',
            field=models.CharField(choices=[('raj', 'raj')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sales_person',
            field=models.CharField(choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], max_length=200, null=True),
        ),
    ]
