# Generated by Django 3.2.5 on 2021-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210719_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_staff',
            field=models.CharField(blank=True, choices=[('raj', 'raj')], max_length=200, null=True),
        ),
    ]
