# Generated by Django 3.2.5 on 2021-08-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_issubscribed'),
        ('subscriptions', '0012_subscription_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product_subscried',
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency_type',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
