# Generated by Django 3.2.5 on 2021-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20210805_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='resume_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sales_person',
            field=models.CharField(blank=True, choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], max_length=200, null=True),
        ),
    ]
