# Generated by Django 3.2.5 on 2021-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='expected_to_resolved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
