# Generated by Django 3.2.5 on 2021-07-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffpersons', '0009_auto_20210720_1723'),
        ('feedbacks', '0002_alter_feedback_expected_to_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='expected_to_resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffpersons.staffperson'),
        ),
    ]
