# Generated by Django 3.2.5 on 2021-08-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_customer_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customertest',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Stafftest',
        ),
    ]
