# Generated by Django 3.2.5 on 2021-08-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_auto_20210818_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
