# Generated by Django 3.2.5 on 2021-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalePersonCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_person', models.CharField(choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], max_length=200)),
                ('commission_percentage', models.IntegerField()),
                ('status', models.CharField(choices=[('unpaid', 'Un-Paid'), ('paid', 'Paid')], max_length=200)),
            ],
        ),
    ]
