# Generated by Django 3.2.5 on 2021-07-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20210721_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepersoncommission',
            name='status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Un-Paid'), ('paid', 'Paid')], max_length=200, null=True),
        ),
    ]
