# Generated by Django 3.2.5 on 2021-08-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_status'),
        ('commissions', '0003_alter_salepersoncommission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amt', models.PositiveIntegerField(default=0)),
                ('commission_percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.salepersoncommission')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
