# Generated by Django 3.2.5 on 2021-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myholidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myholiday',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='myholiday',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
