# Generated by Django 3.2.5 on 2021-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myholidays', '0002_auto_20210809_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myholiday',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myholiday',
            name='startdate',
            field=models.DateField(),
        ),
    ]
