# Generated by Django 3.2.5 on 2021-08-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myholidays', '0003_auto_20210809_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myholiday',
            options={'verbose_name': 'My Plan'},
        ),
    ]
