# Generated by Django 3.2.5 on 2021-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sales_person', models.CharField(blank=True, choices=[('nikhil', 'nikhil'), ('ganesh', 'ganesh')], default=None, max_length=200)),
                ('valid_from_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('buynow', 'Buy Now')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
