# Generated by Django 3.2.5 on 2021-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='dicountper',
            field=models.IntegerField(default=0),
        ),
    ]
