# Generated by Django 3.2.5 on 2021-07-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_rename_dicountper_coupon_discountper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discountper',
            new_name='dis_count_per',
        ),
    ]
