# Generated by Django 3.2.5 on 2021-07-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othermasters', '0003_alter_citymaster_options'),
        ('customers', '0002_auto_20210719_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othermasters.citymaster'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othermasters.societymaster'),
        ),
    ]
