# Generated by Django 3.2.5 on 2021-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210719_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='society',
        ),
    ]
