# Generated by Django 3.2.5 on 2021-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othermasters', '0002_auto_20210719_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymaster',
            options={'ordering': ('-created',)},
        ),
    ]
