# Generated by Django 3.2.5 on 2021-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_sales_person'),
        ('subscriptions', '0004_remove_subscription_sales_person'),
        ('othermasters', '0004_auto_20210719_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymaster',
            name='assign_sale_person',
        ),
        migrations.DeleteModel(
            name='SalePerson',
        ),
    ]
