# Generated by Django 3.2.5 on 2021-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_society'),
        ('customers', '0004_remove_customer_society'),
        ('othermasters', '0005_auto_20210719_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocietyMaster',
        ),
    ]
